kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - name: syslog
      protocol: TCP
      port: 5044
      nodePort: 30044
    - name: beat
      protocol: TCP
      port: 5045
      nodePort: 30045
    - name: http
      protocol: TCP
      port: 5046
      nodePort: 30046
    - name: api
      protocol: TCP
      port: 9600
      nodePort: 30000
