apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
data:
  syslog.conf: |
    input {
      tcp {
        port => 5044
        type => syslog
      }
    }

    filter {
      if [type] == "syslog" {
        grok {
          match => { "message" => "%{SYSLOG5424PRI}%{NONNEGINT:syslog5424_ver} +(?:%{TIMESTAMP_ISO8601:syslog5424_ts}|-) +(?:%{HOSTNAME:syslog5424_host}|-) +(?:%{NOTSPACE:syslog5424_app}|-) +(?:%{NOTSPACE:syslog5424_proc}|-) +(?:%{WORD:syslog5424_msgid}|-) +(?:%{SYSLOG5424SD:syslog5424_sd}|-|) +%{GREEDYDATA:syslog5424_msg}" }
        }
        if !("_grokparsefailure" in [tags]) {
          date {
            match => [ "syslog5424_ts", "ISO8601" ]
          }
          kv {
            remove_char_value => "\[\]\""
            prefix => "tags_"
            source => "syslog5424_sd"
          }
          mutate {
            add_field => {
              "cf_org" => "%{tags_organization_name}"
              "cf_space" => "%{tags_space_name}"
              "cf_app" => "%{tags_app_name}"
              "cf_app_instance" => "%{tags_instance_id}"
              "cf_source" => "%{tags_source_type}"
              "msg" => "%{syslog5424_msg}"
            }
          }
          prune {
            blacklist_names => [ "^syslog5424_", "^tags_", "^host$", "^port$", "^message$" ]
          }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
      }
    }