apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
data:
  syslog.conf: |
    input {
      tcp {
        port => 5044
        type => syslog
      }
    }

    filter {
      if [type] == "syslog" {
        grok {
          match => { "message" => "%{SYSLOG5424PRI}%{NONNEGINT:syslog5424_ver} +(?:%{TIMESTAMP_ISO8601:syslog5424_ts}|-) +(?:%{HOSTNAME:syslog5424_host}|-) +(?:%{NOTSPACE:syslog5424_app}|-) +(?:%{NOTSPACE:syslog5424_proc}|-) +(?:%{WORD:syslog5424_msgid}|-) +(?:%{SYSLOG5424SD:syslog5424_sd}|-|) +%{GREEDYDATA:syslog5424_msg}" }
        }
        if !("_grokparsefailure" in [tags]) {
          date {
            match => [ "syslog5424_ts", "ISO8601" ]
          }
          kv {
            remove_char_value => "\[\]\""
            prefix => "tags_"
            source => "syslog5424_sd"
          }
          mutate {
            copy => { "syslog5424_msg" => "message" }
            copy => { "tags_origanization_name" => "cf_org" }
            copy => { "tags_space_name" => "cf_space" }
            copy => { "tags_app_name" => "cf_app" }
            copy => { "tags_instance_id" => "cf_app_instance" }
            copy => { "syslog5424_msg" => "msg" }
          }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
      }
    }